// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import AppstoreOutlined from '/Users/chaoyang/传说中的神兽/cy/media/code/react/antdPro/node_modules/_@ant-design_icons@4.8.1@@ant-design/icons/es/icons/AppstoreOutlined';
export default { AppstoreOutlined };
