// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/table","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"home","path":"/home","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"用户列表","path":"/table","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"hooks","path":"/hooks","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"echart","path":"/echart","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"*","layout":false,"id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.jsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Table__index" */'@/pages/Table/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__HooksCy__index" */'@/pages/HooksCy/index.jsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__EchartCy__index" */'@/pages/EchartCy/index.jsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/chaoyang/传说中的神兽/cy/media/code/react/antdPro/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
